CUDA_VISIBLE_DEVICES=0 python model_training.py \
    --z_dim 100 \
    --batch_size 32 \
    --num_epochs 200 \
    --learning_rate 9e-4 \
    --loss_function hinge \
    --directory_fake fake \
    --directory_real real \
    --directory_result num_result \
    --input_size 1180 \
    --sequence_length 8 \
    --hidden_size 256 \
    --num_layers 1 \
    --wave_current_dimension 30 \
    --bottom_images 60 \
    --train_data_dir Your_data_directory \
